### ISSUE TITLE
Use docker-machine in swig-docker

### ISSUE THREAD

**Issue by k4sbasia** [gilt/gilt-swig#14]
boot2docker https://github.com/boot2docker/boot2docker-cli is being deprecated in favour of docker-machine https://github.com/docker/machine

moving forward it would be good for swig to use only docker-machine as kitematic https://docs.docker.com/kitematic/ is part of https://www.docker.com/toolbox now and docker machine become a standard.

**Comment by shellscape** [comment]
When boot2docker gets officially obsoleted, we can safely remove it. We should hold off on removing it from swig until then. Additionally, all non-front-end tools may be removed from swig in the near future. Prudent to wait and see how that plays out before making a definitive decision on that.

**Comment by k4sbasia** [comment]
It is officially deprecated now, see the README first paragraph https://github.com/boot2docker/boot2docker-cli

>Deprecated
This project is officially deprecated in favor of Docker Machine. The code and documentation here only exist as a reference for users who have not yet switched over (but please do soon). The recommended way to install Machine is with the Docker Toolbox.

**Comment by shellscape** [comment]
Yes, I understand that. It can remain is swig for folks who have not yet switched over. A good idea to revisit in a few months time.

**Comment by k4sbasia** [comment]
At lease we should consider to switch the order, currently boot2docker is the default one. As more folks are using the docker-machine now, the check for boot2docker first seems not needed.
