### ISSUE TITLE
Running swig after fresh install requests .swigrc

### ISSUE THREAD

**Issue by rcaloras** [gilt/gilt-swig#5]
Was trying to use swig install on an app after freshly installed swig and I got this message:

```bash
 ✖  swig-project: .swigrc not found at: ~/.swigrc. Please grab a copy from /web/tools/config/user.
```

Was thinking it'd be better to perhaps just create an initial default or blank .swigrc containing just '{ }'. Also thought it was strange it showed '/web/toosl/config/user'. As an open source project what's with the proprietary message?

@nathanstilwell What do you think? 

Thanks Andrew!

**Comment by nathanstilwell** [comment]
The `.swigrc` is used for tunneling. It would be nice if it weren't required for other tasks like `swig-install`.

**Comment by shellscape** [comment]
it's not just used for tunneling, there's other data in there that's needed internally for gilt, and it's stuff we can't (or shouldn't) put in a public repo. talked with infra about that and that's what they requested. there's really no other way to go about it - we need proprietary information for stuff to work properly for Gilt.

**Comment by rcaloras** [comment]
What about creating a default or blank .swigrc?

**Comment by shellscape** [comment]
For us, we want the user to take action on first use. Creating a blank file just means to run into trouble down the road (like when you try and run that new shiny app you just created), and you have the same problem with a default file - like one that has labels for properties it needs without legit values.

**Comment by shellscape** [comment]
@rcaloras gonna close this one. if you think of any other issues that need discussing around this, please reopen.
