### ISSUE TITLE
Running swig-install on fresh checkout gives error if gulpfile requires a node module dependency

### ISSUE THREAD

**Issue by kevinoriordan** [gilt/gilt-swig#6]
I have the following code in my gulpfile.js

       var mocha = require('gulp-mocha-co');

       gulp.task('server-spec', function () {
              return gulp.src(['test/**/*.js'], { read: false })
                  .pipe(mocha({reporter: 'spec', ui: 'bdd'}));
       });

And the following in my package.json:

      devDependencies: {
               ...,
               "gulp-mocha-co": "^0.4.1-co.3",
              ...
      }

When I run swig install on a fresh checkout, I get the following error:

         module.js:338
          throw err;
          ^
         Error: Cannot find module 'gulp-mocha-co'

The workaround is the comment out the above section in my gulpfile.js, run the swig install command, then add back in the gulp tasks.

**Comment by shellscape** [comment]
That doesn't make much sense. I have several projects with additional code in the gulpfile. Post that gulpfile in a gist and link to it here please. Also, if you haven't run `swig init` in a fresh clone of web-checkout (or any project), you're going to get errors when attempting to run swig.

**Comment by kevinoriordan** [comment]
Cheers Andrew. Looks like I was missing the swig init bit (as was the Dockerfile I reused from Team Nova so I was seeing the issue when trying to make the Docker image for deploy). Will add "swig init" to my Dockerfile and that should sort things.
